// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqe7qNMY3HE1ffp-O2-PkrPqhN_QVKErc',
    appId: '1:1075110477713:web:10abb30abe752c9992e430',
    messagingSenderId: '1075110477713',
    projectId: 'login-61e0f',
    authDomain: 'login-61e0f.firebaseapp.com',
    databaseURL: 'https://login-61e0f-default-rtdb.firebaseio.com',
    storageBucket: 'login-61e0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdhkDWEBieYYmCI46obQv7cngYzRt_AhI',
    appId: '1:1075110477713:android:f98177a2db324bd492e430',
    messagingSenderId: '1075110477713',
    projectId: 'login-61e0f',
    databaseURL: 'https://login-61e0f-default-rtdb.firebaseio.com',
    storageBucket: 'login-61e0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Qm5ojVoz8ogmYUWd9cPaMEWTO2Qj25c',
    appId: '1:1075110477713:ios:29d2ec140f72d29d92e430',
    messagingSenderId: '1075110477713',
    projectId: 'login-61e0f',
    databaseURL: 'https://login-61e0f-default-rtdb.firebaseio.com',
    storageBucket: 'login-61e0f.appspot.com',
    androidClientId: '1075110477713-4evibmrt7s0bdlbhkcusqhhkutgj95hr.apps.googleusercontent.com',
    iosClientId: '1075110477713-b2l3lc0v0ll8t12dc7icjcu6igpqrqln.apps.googleusercontent.com',
    iosBundleId: 'com.elvis.loginGoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Qm5ojVoz8ogmYUWd9cPaMEWTO2Qj25c',
    appId: '1:1075110477713:ios:29d2ec140f72d29d92e430',
    messagingSenderId: '1075110477713',
    projectId: 'login-61e0f',
    databaseURL: 'https://login-61e0f-default-rtdb.firebaseio.com',
    storageBucket: 'login-61e0f.appspot.com',
    androidClientId: '1075110477713-4evibmrt7s0bdlbhkcusqhhkutgj95hr.apps.googleusercontent.com',
    iosClientId: '1075110477713-b2l3lc0v0ll8t12dc7icjcu6igpqrqln.apps.googleusercontent.com',
    iosBundleId: 'com.elvis.loginGoogle',
  );
}
